### PR TITLE
Fix: rename GridOSHEntity to GridOSHEntities

### PR DESCRIPTION
**Pull request by SlowMo24**
Merge this branch into master **after** serialization has been changed from serializing classes to serializing data.

Being a collection of entities GridOSHEntities should be plural
according to our coding style.

See https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/merge_requests/17

### CODE REVIEW

**Comment by SlowMo24** [comment]
related? #135

**Comment by SlowMo24** [comment]
Fails because https://github.com/GIScience/oshdb/blob/rename-GridOSHEntity/oshdb-util/src/test/resources/test-data.mv.db holds GridOSHEntiy not GridOSHEntities
needs to be updated before merging!

**Comment by rtroilo** [comment]
see new issue #137

**Comment by SlowMo24** [comment]
So the class GridOSHEntities would not exist any more?

**Comment by joker234** [comment]
outdated, closed as suggested before

**Pull request closed without merging**
