### PR TITLE
fix calculation of areas of polygons with inner rings

### LINKED ISSUE #171: Wrong area computation of Multipolygons with holes
**Describe the bug**
The area of a relation is too high.

**To Reproduce**
relation: https://www.openstreetmap.org/relation/5608072/
request to the ohsome API: https://api.ohsome.org/v0.9/elements/area?bboxes=8.688308,49.401807,8.690003,49.403273&format=json&keys=building&time=2019-04-01&types=relation&values=hospital
ohsome API value: 6448.93

**Expected behavior**
To compute correct(ish) results:
geojson.io: 5399.27
geometry from ohsome API in QGIS: 5393.5

**System (please complete the following information):**
browser: chrome Version 74.0.3729.131 (Official Build) (64-bit) on Windows

### PR DESCRIPTION
**Pull request by tyrasd**
fixes #171 (bugfix)

### CODE REVIEW

**Comment by tyrasd** [comment]
we might consider backporting this fix to the 0.5 branch (e.g. by making a 0.5.1 release), since it is a quite important functionality. what do you think? //cc @rtroilo @FabiKo117 @SlowMo24

**Comment by SlowMo24** [comment]
are there any other non-breaking fixes we might include? Wasn't there some documentation update?

**Comment by tyrasd** [comment]
you mean #153?

**Comment by SlowMo24** [comment]
actually looking at the commints, I see no reason to releases the current state of master as 0.5.1

**Pull request merged**
